development:
  sessions:
    default:
      database: acme_corp_development
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: acme_corp_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      database: acme_corp_production
      # heroku
      # uri: <%= ENV['MONGOHQ_URL'] %>
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
